sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start createing an image"
  - docker build -t chulgs15/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true chulgs15/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-267929877047"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY